export const TOGGLE_THEME = "TOGGLE_THEME";
export const SET_LOADER = "SET_LOADER";

export const GET_GRAPH_DATA_CONFIRMED_PENDING = "GET_GRAPH_DATA_CONFIRMED_PENDING";
export const GET_GRAPH_DATA_CONFIRMED_SUCCESS = "GET_GRAPH_DATA_CONFIRMED_SUCCESS";
export const GET_GRAPH_DATA_CONFIRMED_FAILED = "GET_GRAPH_DATA_CONFIRMED_FAILED";