export const TOGGLE_THEME = "TOGGLE_THEME";

export const GET_DASHBOARD_DATA_PENDING = "GET_DASHBOARD_DATA_PENDING";
export const GET_DASHBOARD_DATA_SUCCESS = "GET_DASHBOARD_DATA_SUCCESS";
export const GET_DASHBOARD_DATA_FAILED = "GET_DASHBOARD_DATA_FAILED";

export const LOGIN_ADMIN_PENDING = "LOGIN_ADMIN_PENDING";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAILED = "LOGIN_ADMIN_FAILED";

export const GET_ALL_RESTAURANTS_PENDING = "GET_ALL_RESTAURANTS_PENDING";
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAILED = "GET_ALL_RESTAURANTS_FAILED";

export const GET_DASHBOARD_FILTER_PENDING = "GET_DASHBOARD_FILTER_PENDING";
export const GET_DASHBOARD_FILTER_SUCCESS = "GET_DASHBOARD_FILTER_SUCCESS";
export const GET_DASHBOARD_FILTER_FAILED = "GET_DASHBOARD_FILTER_FAILED";